namespace Kora.Core.Commands;

public enum BuiltInAction
{
    ShowApplication,
    HideApplication,
    ExitApplication,
    RestartApplication,
    OpenSettings,
    OpenDocumentation,
    OpenSetup,
    ShowHelp,
    ShowVersion,
    ShowStatus,
    ShowCurrentTaskProgress,
    CancelTask,
    StopSpeaking,
    LockMachine,
    ProposeShutdown,
    ProposeRestart,
    CancelPowerAction,
    ShowPowerStatus,
    ListGrants,
    ManageGrants,
    ShowModelExecution,
    EnableLocalModels,
    DisableLocalModels,
    EnableHostedModels,
    DisableHostedModels,
}