changelog:
  exclude:
    labels:
      - skip-changelog
      - documentation
      - tests
      - internal
      - ci
  categories:
    - title: Features and improvements
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
    - title: Dependency updates
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
