#requires -Version 7.5
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string] $OutputDirectory,
    [ValidateSet('Prepare', 'Run')][string] $Stage = 'Prepare',
    [string] $PreparedDirectory,
    [Nullable[DateTimeOffset]] $DeadlineUtc,
    [string] $PackageSource,
    [switch] $ApproveDesktopAutomation,
    [switch] $ValidateOnly
)
. (Join-Path $PSScriptRoot 'NativeUxValidation.Common.ps1')
$driverHash = (Get-FileHash -LiteralPath $PSCommandPath).Hash.ToLowerInvariant()
$baselineDriver = Join-Path $PSScriptRoot 'Invoke-NativeUxMechanics.ps1'
$helperHash = (Get-FileHash -LiteralPath $baselineDriver).Hash.ToLowerInvariant()
$acceptance = @(
    'G01-bounded-passive-inventory', 'G02-genuine-native-overflow',
    'G03-selection-refresh-fences', 'G04-stale-use-revision',
    'G05-stale-origin-lifecycle', 'G06-privacy-close-fresh-window',
    'G07-single-revoke-readback-denial', 'G08-unrelated-perpetual-clocks-preserved'
)
if ($Stage -ceq 'Prepare') {
    if ($ApproveDesktopAutomation -or $null -ne $DeadlineUtc -or $ValidateOnly -or $PreparedDirectory) {
        throw 'Prepare accepts no desktop approval, deadline, prepared input or ValidateOnly; it never launches native UI.'
    }
    & (Join-Path $PSScriptRoot 'Invoke-NativeUxValidation.ps1') -Stage Prepare `
        -OutputDirectory $OutputDirectory -PackageSource $PackageSource
    $prepared = Assert-NativeUxBundle $OutputDirectory
    Write-ProofJson ([ordered]@{
        schema = 1; status = 'Prepared'; nativeAcceptance = 'Pending'; windowsLaunched = $false
        approvalStarted = $false; deadlineUtc = $null; source = $prepared.source
        driverSha256 = $driverHash; mechanicsSha256 = $helperHash
        preparationSha256 = (Get-FileHash -LiteralPath (Join-Path $OutputDirectory 'automated.json')).Hash.ToLowerInvariant()
        fixtureMode = '--exact-grants-fixture'; syntheticGrantCount = 51
        grantIds = 'Generated by genuine scratch host approval at later fixture initialization; no native grant IDs exist during Prepare.'
        rows = @($acceptance | ForEach-Object { @{ id = $_; status = 'Pending' } })
        scope = 'Scratch host authority only. No real effect dispatcher; no stopping or rollback promise. Parent retains interactive authority.'
    }) (Join-Path $OutputDirectory 'exact-grants-prepared.json')
    Write-Host 'Exact-grant preparation complete. No native launch/input, no interactive deadline or approval started.'
    return
}
if ($null -eq $DeadlineUtc -or $DeadlineUtc -le [DateTimeOffset]::UtcNow -or
    $DeadlineUtc -gt [DateTimeOffset]::UtcNow.AddHours(1)) {
    throw 'Run requires an explicit future DeadlineUtc no more than one hour away; no approval is inferred.'
}
if (!$ValidateOnly -and !$ApproveDesktopAutomation) {
    throw 'Explicit desktop automation approval is required for Run; preparation is not permission.'
}
$preparedRoot = Assert-NativeUxOutput $PreparedDirectory
$trialRoot = Assert-NativeUxOutput $OutputDirectory
$prepared = Assert-NativeUxBundle $preparedRoot
$exactPreparation = Read-NativeUxJson (Join-Path $preparedRoot 'exact-grants-prepared.json')
if ($exactPreparation.status -cne 'Prepared' -or $exactPreparation.nativeAcceptance -cne 'Pending' -or
    $exactPreparation.driverSha256 -cne $driverHash -or $exactPreparation.mechanicsSha256 -cne $helperHash -or
    $exactPreparation.preparationSha256 -cne (Get-FileHash -LiteralPath (Join-Path $preparedRoot 'automated.json')).Hash.ToLowerInvariant()) {
    throw 'Exact-grant preparation or driver identity changed; prepare fresh, do not run stale bytes.'
}
$source = Get-NativeUxSourceIdentity ([IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..')))
if ($source.revision -cne $prepared.source.revision -or $source.buildInputSha256 -cne $prepared.source.buildInputSha256) {
    throw 'The frozen exact-grant worktree changed after preparation.'
}
& $baselineDriver -PreparedDirectory $preparedRoot -OutputDirectory $trialRoot -DeadlineUtc $DeadlineUtc -ValidateOnly
if ($ValidateOnly) { return }
# Load the maintained helpers without executing their baseline or creating another fixture.
. $baselineDriver -PreparedDirectory $preparedRoot -OutputDirectory $trialRoot -DeadlineUtc $DeadlineUtc -LoadHelpersOnly
New-ProofDirectory $trialRoot
$OutputDirectory = $trialRoot
$scratch = Join-Path $trialRoot 'scratch'
New-Item -ItemType Directory -Path $scratch | Out-Null
$process = [Diagnostics.Process]::new()
$rows = [Collections.Generic.List[object]]::new()
$receipt = [ordered]@{
    schema = 1; status = 'Running'; startedUtc = [DateTimeOffset]::UtcNow.ToString('O')
    deadlineUtc = $DeadlineUtc.ToUniversalTime().ToString('O'); driverSha256 = $driverHash
    mechanicsSha256 = $helperHash; source = $source; processId = $null; readyObserved = $false
    providerReadinessDeferrals = 0; retiredWindowHandles = 0; forcedTermination = $false; scratchCleaned = $false; exitCode = $null
    actionRetries = 0; rows = @(); scope = $exactPreparation.scope
}
$script:fixturePid = 0
$script:launcher = $null
$script:grantWindow = $null
$stopAttempted = $false

function Read-ExactFixture {
    param([string] $Action = 'Inspect synthetic exact grant state')
    $previous = (Get-NamedElement $script:launcher 'Native fixture status' -Prefix).Current.Name
    Invoke-Named $script:launcher $Action
    $null = Wait-Native {
        $text = (Get-NamedElement $script:launcher 'Native fixture status' -Prefix).Current.Name
        $text.Contains('"AuditHead"', [StringComparison]::Ordinal) -and
            (Get-NamedElement $script:launcher $Action).Current.IsEnabled -and
            $text -cne $previous
    } "completed exact fixture observation $Action"
    $text = (Get-NamedElement $script:launcher 'Native fixture status' -Prefix).Current.Name
    $start = $text.IndexOf('{', [StringComparison]::Ordinal)
    if ($start -lt 0) { throw 'Exact fixture observation has no JSON object.' }
    $wrapper = $text.Substring($start) | ConvertFrom-Json -AsHashtable -DateKind String
    if ($wrapper.ObservationSequence -le 0 -or $null -eq $wrapper.State) { throw 'No completed exact observation identity.' }
    $wrapper.State
}
function Exact-Role {
    param($Observation, [string] $Name)
    $role = @($Observation.Roles | Where-Object Name -CEQ $Name)
    if ($role.Count -ne 1) { throw "One exact fixture role is required: $Name" }
    $role[0]
}
function Exact-Text {
    param([string] $Name)
    (Get-NamedElement $script:grantWindow $Name -Prefix).Current.Name
}
function Exact-List { Get-NamedElement $script:grantWindow 'Retained exact operation grants' }
function Exact-Items {
    $list = Exact-List
    Assert-OwnedElement $list
    @($list.FindAll([Windows.Automation.TreeScope]::Descendants,
        [Windows.Automation.PropertyCondition]::new([Windows.Automation.AutomationElement]::ControlTypeProperty,
            [Windows.Automation.ControlType]::ListItem)))
}
function Exact-DisplayedId {
    param([string[]] $Text)
    $ids = @($Text | Where-Object { $_ -cmatch '\A[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}\z' } |
        Sort-Object -Unique)
    if ($ids.Count -ne 1) { throw 'A retained native list item must disclose one exact approval ID.' }
    $ids[0]
}
function Exact-ItemId {
    param([Windows.Automation.AutomationElement] $Item)
    Assert-OwnedElement $Item
    $text = @($Item.FindAll([Windows.Automation.TreeScope]::Descendants,
        [Windows.Automation.PropertyCondition]::new([Windows.Automation.AutomationElement]::ControlTypeProperty,
            [Windows.Automation.ControlType]::Text)) | ForEach-Object { $_.Current.Name })
    Exact-DisplayedId $text
}
function Discover-ExactPage {
    param([string] $FindId)
    $list = Exact-List
    $scroll = $null
    $scrollable = $list.TryGetCurrentPattern([Windows.Automation.ScrollPattern]::Pattern, [ref]$scroll) -and $scroll.Current.VerticallyScrollable
    $positions = @(0)
    if ($scrollable) {
        $view = $scroll.Current.VerticalViewSize
        Check-Native ($view -gt 0 -and $view -lt 100) 'Native discovery requires a genuine bounded viewport.'
        $step = [Math]::Max(1, [Math]::Min(5, [Math]::Floor($view / 2)))
        $positions = @(0..100 | Where-Object { $_ % $step -eq 0 -or $_ -eq 100 })
    }
    $ids = [Collections.Generic.HashSet[string]]::new()
    foreach ($position in $positions) {
        Assert-OwnedElement $list
        if ($scrollable) {
            $scroll.SetScrollPercent([Windows.Automation.ScrollPattern]::NoScroll, $position)
            $null = Wait-Native { [Math]::Abs($scroll.Current.VerticalScrollPercent - $position) -lt 1 } 'bounded native list discovery scroll'
        }
        foreach ($item in Exact-Items) {
            $id = Exact-ItemId $item
            $null = $ids.Add($id)
            if ($FindId -and $id -ceq $FindId) { return $item }
        }
    }
    if (!$FindId) { @($ids | Sort-Object) }
}
function Wait-ExactReady {
    $null = Wait-Native {
        (Get-NamedElement $script:grantWindow 'Refresh exact grant inventory').Current.IsEnabled -and
            @(Exact-Items).Count -gt 0
    } 'bounded exact grant page completed'
}
function Refresh-Exact {
    Invoke-Named $script:grantWindow 'Refresh exact grant inventory'
    $null = Wait-Native {
        (Exact-Text 'Current exact grant inspection').Contains('Select one exact retained ID', [StringComparison]::Ordinal)
    } 'refresh discarded exact review'
    Wait-ExactReady
}
function Next-Exact {
    $before = @(Exact-Items | ForEach-Object { Exact-ItemId $_ }) -join ','
    Invoke-Named $script:grantWindow 'Read next bounded exact grant page'
    $null = Wait-Native {
        @(Exact-Items).Count -gt 0 -and
            (@(Exact-Items | ForEach-Object { Exact-ItemId $_ }) -join ',') -cne $before
    } 'next distinct bounded native page'
    Wait-ExactReady
}
function Select-Exact {
    param([string] $Id)
    Refresh-Exact
    for ($page = 0; $page -lt 51; $page++) {
        $items = @(Discover-ExactPage -FindId $Id)
        if ($items.Count -gt 1) { throw 'Exact native selection is ambiguous.' }
        if ($items.Count -eq 1) {
            Assert-OwnedElement $items[0]
            $selection = [Windows.Automation.SelectionItemPattern]$items[0].GetCurrentPattern([Windows.Automation.SelectionItemPattern]::Pattern)
            $selection.Select()
            $null = Wait-Native {
                $selection.Current.IsSelected -and (Get-NamedElement $script:grantWindow 'Inspect current selected exact grant ID').Current.IsEnabled
            } 'current exact native selection'
            Invoke-Named $script:grantWindow 'Inspect current selected exact grant ID'
            $null = Wait-Native {
                (Exact-Text 'Current exact grant inspection').Contains("Approval ID: $Id;", [StringComparison]::Ordinal) -and
                    (Get-NamedElement $script:grantWindow 'Inspect current selected exact grant ID').Current.IsEnabled
            } 'fresh exact ID inspection'
            return
        }
        if (!(Get-NamedElement $script:grantWindow 'Read next bounded exact grant page').Current.IsEnabled) { break }
        Next-Exact
    }
    throw "Exact native grant ID was not discovered in the bounded inventory: $Id"
}
function Review-Exact {
    Invoke-Named $script:grantWindow 'Explicit confirmation of the displayed exact approval ID and revision'
    $null = Wait-Native {
        (Get-NamedElement $script:grantWindow 'Confirm revocation of only this exact inspected ID and revision').Current.IsEnabled
    } 'explicit exact native review enabled'
}
function Confirm-Exact {
    param([switch] $Stale)
    Invoke-Named $script:grantWindow 'Confirm revocation of only this exact inspected ID and revision'
    $expected = if ($Stale) { 'Exact preview is stale' } else { 'Exact revocation committed and read back' }
    $null = Wait-Native { (Exact-Text 'Exact grant operation status').Contains($expected, [StringComparison]::Ordinal) } $expected
    Check-Native (!(Get-NamedElement $script:grantWindow 'Confirm revocation of only this exact inspected ID and revision').Current.IsEnabled) 'Exact confirmation must retire after one action.'
}

try {
    $process.StartInfo.FileName = Join-Path $preparedRoot 'payload\Kora.NativeUxFixture.exe'
    $process.StartInfo.WorkingDirectory = Join-Path $preparedRoot 'payload'
    $process.StartInfo.UseShellExecute = $false
    $process.StartInfo.RedirectStandardOutput = $true
    $process.StartInfo.RedirectStandardError = $true
    foreach ($argument in '--launch-native-fixtures', '--scratch-parent', $scratch, '--exact-grants-fixture') {
        $process.StartInfo.ArgumentList.Add($argument)
    }
    Assert-NativeUxProfile
    if ([DateTimeOffset]::UtcNow -ge $DeadlineUtc) { throw 'Desktop deadline expired before launch.' }
    if (!$process.Start()) { throw 'The optional scratch exact-grant fixture did not start.' }
    $receipt.processId = $process.Id
    $script:fixturePid = $process.Id
    $stdout = $process.StandardOutput.ReadToEndAsync()
    $stderr = $process.StandardError.ReadToEndAsync()
    $script:launcher = Wait-Native {
        $found = @(Get-OwnedWindows | Where-Object { $_.Current.Name -cin @(
            'Kora synthetic native UX fixture launcher', 'Kora SYNTHETIC native UX fixture - not the production host') })
        if ($found.Count -eq 1) { $found[0] }
    } 'owned exact-grant launcher'
    $null = Wait-Native {
        (Get-NamedElement $script:launcher 'Native fixture status' -Prefix).Current.Name.Contains('READY:', [StringComparison]::Ordinal)
    } 'genuine scratch approval initialization' -Seconds 120
    $receipt.readyObserved = $true
    $before = Read-ExactFixture
    $receipt.initial = $before
    $target = (Exact-Role $before 'target').Inspection.Grant.Id.Value
    $used = (Exact-Role $before 'used').Inspection.Grant.Id.Value
    $lifecycle = (Exact-Role $before 'lifecycle').Inspection.Grant.Id.Value
    $script:grantWindow = Open-Window 'Exact grants (scratch host-issued records only)' 'Exact operation grants'
    Wait-ExactReady
    Trial $acceptance[0] {
        Refresh-Exact
        $seen = [Collections.Generic.HashSet[string]]::new()
        $pageSizes = [Collections.Generic.List[int]]::new()
        for ($page = 0; $page -lt 51; $page++) {
            $ids = @(Discover-ExactPage)
            Check-Native ($ids.Count -gt 0 -and $ids.Count -le 50) 'Native page must be nonempty and bounded to at most 50 records.'
            $pageSizes.Add($ids.Count)
            foreach ($id in $ids) { Check-Native ($seen.Add($id)) 'Bounded native inventory duplicated an exact ID.' }
            if (!(Get-NamedElement $script:grantWindow 'Read next bounded exact grant page').Current.IsEnabled) { break }
            Next-Exact
        }
        Check-Native ($seen.Count -eq 51 -and $pageSizes.Count -gt 1) 'Native bounded pages must discover all 51 genuine exact IDs.'
        Select-Exact $target
        Check-Native ((Exact-Text 'Current exact grant inspection').Contains('Current applicability and running-work status are unknown', [StringComparison]::Ordinal)) 'Inspection cannot claim applicability or running-effect status.'
        Check-Native (!(Get-NamedElement $script:grantWindow 'Confirm revocation of only this exact inspected ID and revision').Current.IsEnabled) 'Passive inspection cannot authorize revocation.'
        $passive = Read-ExactFixture
        Check-Native (($passive | ConvertTo-Json -Depth 30 -Compress) -ceq ($before | ConvertTo-Json -Depth 30 -Compress)) 'Passive paging and inspection must preserve audit head, grants and retention clocks.'
        @{ exactIds = @($seen); pageSizes = @($pageSizes); passiveAuthorityUnchanged = $true }
    }
    Refresh-Exact
    $overflowIds = @(Discover-ExactPage)
    Check-Native ($overflowIds.Count -gt 1) 'Overflow discovery must use the populated first bounded page, not a possible single-record final page.'
    $overflowId = $overflowIds[0]
    Select-Exact $overflowId
    $scroll = $null
    $list = Exact-List
    $available = $list.TryGetCurrentPattern([Windows.Automation.ScrollPattern]::Pattern, [ref]$scroll) -and $scroll.Current.VerticallyScrollable
    if ($available) {
        Trial $acceptance[1] {
            Check-Native ($scroll.Current.VerticalViewSize -gt 0 -and $scroll.Current.VerticalViewSize -lt 100) 'Overflow needs a genuine native viewport smaller than its extent.'
            $view = $scroll.Current.VerticalViewSize
            foreach ($percent in 100, 0) {
                Assert-OwnedElement $list
                $scroll.SetScrollPercent([Windows.Automation.ScrollPattern]::NoScroll, $percent)
                $null = Wait-Native { [Math]::Abs($scroll.Current.VerticalScrollPercent - $percent) -lt 1 } 'native list scrollbar endpoint'
            }
            Check-Native ((Exact-Text 'Current exact grant inspection').Contains("Approval ID: $overflowId;", [StringComparison]::Ordinal)) 'Native scrolling cannot retarget the exact preview.'
            @{ inspectedId = $overflowId; nativeVerticalViewSize = $view; endpoints = @(100, 0); fabricatedOverflow = $false }
        }
    } else {
        $rows.Add(@{ id = $acceptance[1]; status = 'Blocked'; reason = 'No genuine overflowing native ScrollPattern was exposed; no simulated scrollbar pass.' })
    }
    Trial $acceptance[2] {
        Review-Exact
        Select-Exact $used
        Check-Native (!(Get-NamedElement $script:grantWindow 'Confirm revocation of only this exact inspected ID and revision').Current.IsEnabled) 'Selection must retire review.'
        Review-Exact
        Refresh-Exact
        Check-Native (!(Get-NamedElement $script:grantWindow 'Confirm revocation of only this exact inspected ID and revision').Current.IsEnabled) 'Refresh must retire review.'
        @{ selectionAndRefreshRetiredReview = $true }
    }
    Trial $acceptance[3] {
        Select-Exact $used
        Review-Exact
        $changed = Read-ExactFixture 'Consume synthetic use target once without effect dispatch'
        Confirm-Exact -Stale
        $role = Exact-Role $changed 'used'
        Check-Native ($role.Inspection.Grant.Revision.Value -eq 2 -and $role.Inspection.Grant.UseCount -eq 1) 'Authority-only use must change the displayed exact revision, not dispatch an effect.'
        @{ exactId = $used; currentRevision = 2; effectsDispatched = 0 }
    }
    Trial $acceptance[4] {
        Select-Exact $lifecycle
        Review-Exact
        $changed = Read-ExactFixture 'End synthetic grant origin without selection refresh'
        Confirm-Exact -Stale
        Check-Native (!(Exact-Role $changed 'lifecycle').Inspection.OriginSession.IsActive) 'The genuine origin lifecycle must be Done.'
        @{ exactId = $lifecycle; staleOriginRefused = $true }
    }
    Trial $acceptance[5] {
        Select-Exact $target
        Review-Exact
        Invoke-Named $script:launcher 'Close synthetic privacy/ownership gate'
        $null = Wait-Native { @(Get-OwnedWindows | Where-Object { $_.Current.Name -ceq 'Exact operation grants' }).Count -eq 0 } 'privacy retires exact private window'
        Invoke-Named $script:launcher 'Reopen synthetic gate (no audio recovery)'
        $null = Wait-Native { (Get-NamedElement $script:launcher 'Exact grants (scratch host-issued records only)').Current.IsEnabled } 'fresh synthetic privacy admission'
        $script:grantWindow = Open-Window 'Exact grants (scratch host-issued records only)' 'Exact operation grants'
        Wait-ExactReady
        Check-Native (!(Get-NamedElement $script:grantWindow 'Confirm revocation of only this exact inspected ID and revision').Current.IsEnabled) 'A reopened window cannot inherit reviewed authority.'
        @{ realOsTransition = $false; previousWindowRetired = $true; staleReviewNotReplayed = $true }
    }
    Trial $acceptance[6] {
        Select-Exact $target
        Review-Exact
        Confirm-Exact
        Check-Native ((Exact-Text 'Exact grant operation status').Contains('not stopped or rolled back', [StringComparison]::Ordinal)) 'Revocation must not promise stopping or rollback.'
        Select-Exact $target
        $text = Exact-Text 'Current exact grant inspection'
        Check-Native ($text.Contains('revision: 2', [StringComparison]::Ordinal) -and
            $text.Contains('Stored status: Revoked', [StringComparison]::Ordinal) -and
            $text.Contains('Use count: 0', [StringComparison]::Ordinal)) 'Exact revoked record must be read back with unchanged zero use count.'
        $denied = Read-ExactFixture 'Probe subsequent revoked target consume denial without effects'
        Check-Native ($denied.ConsumeOutcomeName -ceq 'Conflict') 'Subsequent genuine authority consume must be denied as Conflict.'
        @{ exactId = $target; revision = 2; consumeOutcome = $denied.ConsumeOutcomeName; effectsDispatched = 0 }
    }
    Trial $acceptance[7] {
        Close-OwnedWindow $script:grantWindow
        $script:grantWindow = Open-Window 'Exact grants (scratch host-issued records only)' 'Exact operation grants'
        Wait-ExactReady
        Select-Exact $target
        $after = Read-ExactFixture
        Check-Native ($after.UnrelatedSha256 -ceq $before.UnrelatedSha256) 'All 48 unrelated grants, including Perpetual, must remain byte-equivalent.'
        foreach ($name in 'target', 'perpetual') {
            $old = Exact-Role $before $name
            $new = Exact-Role $after $name
            Check-Native (($old.Retention.State | ConvertTo-Json -Depth 10 -Compress) -ceq
                ($new.Retention.State | ConvertTo-Json -Depth 10 -Compress)) 'Inspection/revocation cannot renew recorded meaningful-activity/archive/delete clocks.'
        }
        $receipt.final = $after
        @{ unrelatedCount = 48; perpetualUnchanged = $true; clocksRenewed = $false; reopenedReadback = $true }
    }
    Close-OwnedWindow $script:grantWindow
    $stopAttempted = $true
    Invoke-Named $script:launcher 'Stop native fixture and clean up scratch state'
    if (!$process.WaitForExit(15000)) { throw 'Owned fixture did not stop normally.' }
    $receipt.exitCode = $process.ExitCode
    $receipt.scratchCleaned = @(Get-ChildItem -LiteralPath $scratch -Force).Count -eq 0
    if ($receipt.exitCode -ne 0 -or !$receipt.scratchCleaned -or $stderr.GetAwaiter().GetResult().Length -gt 0) {
        throw 'Exact fixture cleanup or stderr failed; inspect durable local output.'
    }
    $null = Assert-NativeUxBundle $preparedRoot
    $receipt.status = if (@($rows | Where-Object status -CEQ 'Blocked').Count) { 'Partial' } else { 'Pass' }
}
catch {
    $receipt.status = 'Failed'
    $receipt.failure = $_.Exception.Message
    $receipt.failureType = $_.Exception.GetType().FullName
    if ($null -ne $_.Exception.InnerException) {
        $receipt.innerFailureType = $_.Exception.InnerException.GetType().FullName
        $receipt.innerFailureHResult = $_.Exception.InnerException.HResult
    }
    throw
}
finally {
    if ($null -ne $receipt.processId -and !$process.HasExited) {
        try {
            if (!$stopAttempted -and $null -ne $script:launcher -and [DateTimeOffset]::UtcNow -lt $DeadlineUtc) {
                $stopAttempted = $true
                Invoke-Named $script:launcher 'Stop native fixture and clean up scratch state'
            }
            if (!$process.WaitForExit(15000)) {
                $receipt.forcedTermination = $true
                Stop-Process -Id $receipt.processId -ErrorAction Stop
                $process.WaitForExit()
            }
        } catch {
            $receipt.cleanupFailure = $_.Exception.Message
            if (!$process.HasExited) {
                $receipt.forcedTermination = $true
                Stop-Process -Id $receipt.processId -ErrorAction Stop
                $process.WaitForExit()
            }
        }
        $receipt.status = 'Failed'
    }
    if ($null -ne $receipt.processId) {
        $receipt.exitCode = $process.ExitCode
        $receipt.scratchCleaned = @(Get-ChildItem -LiteralPath $scratch -Force).Count -eq 0
        [IO.File]::WriteAllText((Join-Path $trialRoot 'stdout.local.txt'), $stdout.GetAwaiter().GetResult())
        [IO.File]::WriteAllText((Join-Path $trialRoot 'stderr.local.txt'), $stderr.GetAwaiter().GetResult())
    }
    $process.Dispose()
    $receipt.rows = @($rows)
    $receipt.completedUtc = [DateTimeOffset]::UtcNow.ToString('O')
    Write-ProofJson $receipt (Join-Path $trialRoot 'exact-grants.json')
}
Write-Host "Exact native grant proof $($receipt.status). Synthetic mechanics only; real effects and real privacy qualification excluded."
