<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Kora.Core\Kora.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference
        Include="KokoroSharp"
        ExcludeAssets="build;buildTransitive;contentFiles" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" />
    <PackageReference Include="MisakiSharp" />
    <PackageReference Include="NAudio" />
    <PackageReference Include="System.Speech" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kora.Windows.IntegrationTests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
